apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: techielins/spring-boot-demo:15   #15 has to be replaced with exact tag of the image for deployment using ArgoCD. There are couple of ways you can
                                                             #automate this stuff.
        ports:
        - containerPort: 8080
